/**
 * The coefficient-aware half of the second necessary condition, decided exactly.
 *
 * R61's flattening screen bounds the dimension of the axis slices; R62's box cover bounds the
 * number of support boxes. Both are coefficient-free: they cannot see the values. The
 * condition implemented here does see them, and it is the one R61 named as missing: "each
 * column of the residual coefficient matrix must also reshape to rank <= 1".
 *
 * THE CONDITION. Write D = M - sum(surviving) for the deficit, and suppose
 *
 *     D[a][b][c] = sum_{t=1..j} u_t[a] v_t[b] w_t[c].                                  (*)
 *
 * Flatten (*) along axis c: D_c[(a,b)][c] = sum_t (u_t (x) v_t)[(a,b)] w_t[c]. So
 *
 *     col(D_c) is contained in col(X),  X = [ x_1 | ... | x_j ],  x_t = u_t (x) v_t,
 *
 * and each column x_t of X reshapes to a 3x3 matrix of rank exactly 1 (rank 0 only for a
 * degenerate term). Writing S_c for the span of all columns of all D_c:
 *
 *   (C1) dim S_c <= j for every axis c, and
 *   (C2) if dim S_c == j then col(X) == S_c exactly, so S_c must be spanned by j linearly
 *        independent vectors each of which reshapes to rank <= 1.                   <== THIS
 *
 * (C2) is the coefficient-aware half. The rank-1 reshaped vectors inside a d-dimensional
 * subspace of Q^9 are the intersection of that subspace with the Segre variety: the zeros of the
 * nine 2x2 minors of M(lambda) = sum_i lambda_i M_i, which are nine homogeneous quadrics in
 * lambda. Deciding whether S_c is spanned by d of them is a quadratic-form problem, and the
 * regimes where that decision is COMPLETE (never a sample) are:
 *
 *   d = 1: one projective point (1); it survives iff every minor coefficient vanishes.
 *   d = 2: P^1 is the chart y = 1 plus the single point (1,0) at y = 0, and on the chart the
 *           first non-degenerate conic has at most two rational roots, found exactly by
 *           discriminant plus a rational-square test, with the other eight filtering them.
 *           Both charts are solved, so the point list is exhaustive and `complete` is true.
 *   d = 3: NOT complete. When a 3-dimensional span is generated by rank-1 matrices, the Segre
 *           intersection can be a positive-dimensional curve in P^2; enumerating the roots of a
 *           single conic then returns a couple of points of a set whose rank-1 members are
 *           precisely the ones that matter. Several charts are still enumerated so the common
 *           case finds its witnesses, but `complete` is false and a `spanned: false` at d = 3 is
 *           NOT a refutation.
 *   d >= 4: a chart leaves at least three free parameters and the minors are no longer
 *           degree-limited, so a complete solve needs a Groebner basis. `complete` is false.
 *
 * Honest scope. A refutation is admissible only when `complete` is true, i.e. only at d <= 2.
 * Such a refutation is exact: S_c admits no spanning set of rank-1 reshaped vectors, so (*) is
 * impossible over Q, hence over Z, hence over every field. It is NOT a claim about rank 22
 * itself. `complete: false` carries no negative information whatsoever.
 *
 * Two further limits, both load-bearing. First, (C2) is only FORCED when dim S_c == j: if
 * dim S_c < j then col(X) is a strictly larger unknown space and S_c need not itself be spanned
 * by rank-1 vectors, so a caller must never read a refutation off an axis whose dim is below j.
 * Second, exactness. Everything here is rational Gaussian elimination and integer square roots
 * over BigInt. No float is compared for equality anywhere, and no float decides membership in a
 * variety.
 */

import { fDiv, fMul, fOne, fSub, fZero, isZero, rref } from "./rational"
import type { Fraction } from "./rational"

export const DIM9 = 9

const PAIRS: readonly (readonly [number, number])[] = (() => {
  const out: (readonly [number, number])[] = []
  for (let i = 0; i < DIM9; i += 1) for (let k = i + 1; k < DIM9; k += 1) out.push([i, k])
  return out
})()

// -------------------------------------------------------------------------------------
// Rational helpers local to this file. rational.ts has no fAdd; keeping these here avoids
// touching a shared tool whose behaviour other rounds' tests judge.
// -------------------------------------------------------------------------------------

export function fAdd(a: Fraction, b: Fraction): Fraction {
  return reduce(a.n * b.d + b.n * a.d, a.d * b.d)
}

export function reduce(n: bigint, d: bigint): Fraction {
  if (d === 0n) throw new RangeError("zero denominator")
  const sign = d < 0n ? -1n : 1n
  let nn = n * sign
  let dd = d * sign
  if (nn === 0n) return fZero()
  let x = nn < 0n ? -nn : nn
  let y = dd
  while (y !== 0n) {
    const t = x % y
    x = y
    y = t
  }
  if (x > 1n) {
    nn /= x
    dd /= x
  }
  return { n: nn, d: dd }
}

export function fInt(n: number): Fraction {
  return reduce(BigInt(n), 1n)
}

export function fNeg(a: Fraction): Fraction {
  return reduce(-a.n, a.d)
}

/** Exact integer square root of a non-negative bigint. */
export function isqrt(x: bigint): bigint {
  if (x < 0n) throw new RangeError("isqrt of a negative")
  if (x < 4n) return x
  let lo = 2n
  let hi = x
  while (lo <= hi) {
    const mid = (lo + hi) / 2n
    const sq = mid * mid
    if (sq === x) return mid
    if (sq < x) lo = mid + 1n
    else hi = mid - 1n
  }
  return hi
}

function isRationalSquare(f: Fraction): boolean {
  if (f.n < 0n) return false
  const rn = isqrt(f.n)
  const rd = isqrt(f.d)
  return rn * rn === f.n && rd * rd === f.d
}

function sqrtExact(f: Fraction): Fraction | null {
  if (!isRationalSquare(f)) return null
  return reduce(isqrt(f.n), isqrt(f.d))
}

/** -1, 0 or 1 according to the sign of a rational. */
export function signOf(f: Fraction): -1 | 0 | 1 {
  if (isZero(f)) return 0
  return f.n < 0n ? -1 : 1
}

// -------------------------------------------------------------------------------------
// Small exact linear algebra
// -------------------------------------------------------------------------------------

/**
 * View a 9-vector x as the 9x9 matrix X[a][b] = x[9a+b].
 *
 * This is the right shape, and getting it wrong is the whole ballgame: the vectors under test
 * are x_t = u_t (x) v_t, which are 9x9 outer products, so "reshapes to rank <= 1" means rank
 * <= 1 as a 9x9 matrix. Reinterpreting the nine coordinates as 3x3 instead describes a
 * scrambled re-indexing under which outer products need not have rank 1, and the screen then
 * "confirms" rank-1 vectors that are not rank 1.
 */
export function toMat9(v: readonly Fraction[]): Fraction[][] {
  const out: Fraction[][] = []
  for (let a = 0; a < DIM9; a += 1) {
    const row: Fraction[] = []
    for (let b = 0; b < DIM9; b += 1) row.push(v[DIM9 * a + b] ?? fZero())
    out.push(row)
  }
  return out
}

/** Exact rank of a rational matrix. */
export function rankOf(m: readonly (readonly Fraction[])[]): number {
  return rref(m.map((row) => [...row])).rank
}

/** Exact basis of the ROW space of a matrix: the nonzero rows of its reduced echelon form. */
export function rowSpaceBasis(rows: readonly (readonly Fraction[])[]): Fraction[][] {
  const width = rows[0]?.length ?? 0
  if (width === 0) return []
  const reduced = rref(rows.map((row) => {
    const out: Fraction[] = []
    for (let c = 0; c < width; c += 1) out.push(row[c] ?? fZero())
    return out
  }))
  const basis: Fraction[][] = []
  for (let i = 0; i < reduced.rank; i += 1) basis.push(reduced.rows[i] ?? [])
  return basis
}

/** Are p and q proportional, i.e. the same projective point? */
export function sameProjective(p: readonly Fraction[], q: readonly Fraction[]): boolean {
  let first = -1
  for (let t = 0; t < p.length; t += 1) {
    if (!isZero(p[t] ?? fZero()) || !isZero(q[t] ?? fZero())) {
      first = t
      break
    }
  }
  if (first < 0) return true
  const pf = p[first] ?? fZero()
  const qf = q[first] ?? fZero()
  for (let t = 0; t < p.length; t += 1) {
    const cross = fSub(fMul(pf, q[t] ?? fZero()), fMul(qf, p[t] ?? fZero()))
    if (!isZero(cross)) return false
  }
  return true
}

/** Largest number of linearly independent vectors in a small exact list, by greedy selection. */
export function independentCount(points: readonly (readonly Fraction[])[]): number {
  const chosen: Fraction[][] = []
  for (const p of points) {
    if (chosen.length === 0) {
      chosen.push([...p])
      continue
    }
    const before = rref(chosen.map((r) => [...r])).rank
    const after = rref([...chosen.map((r) => [...r]), [...p]]).rank
    if (after > before) chosen.push([...p])
  }
  return chosen.length
}

// -------------------------------------------------------------------------------------
// The Segre variety in projective coordinates
// -------------------------------------------------------------------------------------

/**
 * Nine symmetric d x d matrices Q, one per 2x2 minor, with
 *   lambda^T Q lambda = the (rows r1 r2, cols c1 c2) minor of sum_i lambda_i M_i.
 * All nine minors vanish iff lambda^T Q lambda = 0 for every Q.
 *
 * The minor is a*d - b*c with a = M[r1][c1], b = M[r1][c2], c = M[r2][c1], d = M[r2][c2], so
 * Q[i][k] = M_i[r1][c1] M_k[r2][c2] - M_i[r1][c2] M_k[r2][c1]. Pairing each factor with the
 * SAME coordinate on both indices keeps Q symmetric (as it must be, since lambda^T Q lambda is
 * a scalar). Swapping c1 and c2 on the second factor yields an antisymmetric Q, which makes
 * lambda^T Q lambda vanish identically and silently turns every "refutation" into a lie.
 */
export function segreQuadrics(basis: readonly (readonly Fraction[])[]): Fraction[][][] {
  const d = basis.length
  const mats = basis.map(toMat9)
  const quads: Fraction[][][] = []
  for (const [r1, r2] of PAIRS) {
    for (const [c1, c2] of PAIRS) {
      const out: Fraction[][] = []
      for (let i = 0; i < d; i += 1) {
        const row: Fraction[] = []
        for (let k = 0; k < d; k += 1) row.push(fZero())
        out.push(row)
      }
      for (let i = 0; i < d; i += 1) {
        for (let k = 0; k < d; k += 1) {
          const Mi = mats[i]
          const Mk = mats[k]
          if (Mi === undefined || Mk === undefined) continue
          const row = out[i]
          if (row === undefined) continue
          const pos = fMul(Mi[r1]?.[c1] ?? fZero(), Mk[r2]?.[c2] ?? fZero())
          const neg = fMul(Mi[r1]?.[c2] ?? fZero(), Mk[r2]?.[c1] ?? fZero())
          row[k] = fAdd(row[k] ?? fZero(), fSub(pos, neg))
        }
      }
      quads.push(out)
    }
  }
  return quads
}

/** True iff at least one minor of sum_i lambda_i M_i is nonzero, i.e. lambda leaves the Segre set. */
export function outsideSegre(quads: readonly (readonly (readonly Fraction[])[])[], lam: readonly Fraction[]): boolean {
  for (const Q of quads) {
    let acc = fZero()
    for (let i = 0; i < lam.length; i += 1) {
      const li = lam[i] ?? fZero()
      if (isZero(li)) continue
      for (let k = 0; k < lam.length; k += 1) {
        const Qik = Q[i]?.[k] ?? fZero()
        if (isZero(Qik)) continue
        acc = fAdd(acc, fMul(Qik, fMul(li, lam[k] ?? fZero())))
      }
    }
    if (!isZero(acc)) return true
  }
  return false
}

type Conic = readonly [Fraction, Fraction, Fraction]

/**
 * Common projective zeros in P^1 of a x^2 + B x y + c y^2, EXHAUSTIVE.
 * Charts used: y = 1, where the first non-degenerate conic is solved by the quadratic formula
 * with an exact discriminant and the rest filter the roots; and y = 0, the single point (1,0).
 */
export function conicP1Zeros(quads: readonly Conic[]): Fraction[][] {
  const vanishes = (x: Fraction, y: Fraction): boolean => {
    const x2 = fMul(x, x)
    const xy = fMul(x, y)
    const y2 = fMul(y, y)
    for (const [a, b, c] of quads) {
      if (!isZero(fAdd(fAdd(fMul(a, x2), fMul(b, xy)), fMul(c, y2)))) return false
    }
    return true
  }
  const found: Fraction[][] = []
  let roots: Fraction[] | null = null
  for (const [a, b, c] of quads) {
    if (isZero(a) && isZero(b)) continue // the identically-zero conic carries no information
    if (isZero(a)) {
      roots = [fDiv(fNeg(c), b)] // b != 0 here, since a == 0 == 0 was already skipped
    } else {
      const disc = fSub(fMul(b, b), fMul(fInt(4), fMul(a, c)))
      const s = signOf(disc)
      const sq = s < 0 ? null : sqrtExact(disc)
      if (sq === null) {
        // No rational point on the y = 1 chart. Do NOT return: the chart y = 0 may still hold
        // one, and returning early here silently drops it.
        roots = []
      } else {
        const denom = fMul(fInt(2), a)
        roots = [fDiv(fAdd(fNeg(b), sq), denom), fDiv(fSub(fNeg(b), sq), denom)]
      }
    }
    break
  }
  if (roots !== null) for (const x of roots) if (vanishes(x, fOne())) found.push([x, fOne()])
  if (quads.every(([a]) => isZero(a))) found.push([fOne(), fZero()])
  const uniq: Fraction[][] = []
  for (const p of found) if (!uniq.some((q) => sameProjective(q, p))) uniq.push(p)
  return uniq
}

export type SegreSpanResult = {
  /** False only for d >= 4, where the point list would not be exhaustive. */
  readonly complete: boolean
  readonly dim: number
  /** Every projective lambda, up to scale, whose reshape has rank <= 1. Exhaustive when complete. */
  readonly points: readonly (readonly Fraction[])[]
  /** True iff `points` contains `dim` linearly independent members. */
  readonly spanned: boolean
}

/**
 * S_axis for a sparse 9x9x9 deficit: the span of the vectors obtained by fixing the axis
 * coordinate, i.e. of { D[(p),(q),(s)] indexed by (p,q) : s }.
 *
 * This is the span (C2) is about, and the transpose matters: the slice D_s is a 9x9 matrix
 * whose rows are indexed by the OTHER two coordinates, so the wanted span is the row space of
 * the stack of slices, which is the column space of the 81 x 9 matrix with those rows as rows.
 * Building it the other way round silently yields the span along the wrong axis, which looks
 * plausible and refutes nothing real.
 */
export function axisSegreBasis(
  D: ReadonlyMap<number, number>,
  axis: 0 | 1 | 2,
): Fraction[][] {
  // Rows indexed by s (the axis coordinate), columns by the observed pair (p,q). The row space is
  // then exactly span{ D[s][p][q] indexed by (p,q) }, the space (C2) constrains. Transposing
  // this yields span{ D[p][q][s] indexed by s } = span of the axis factor, which reshapes to
  // rank u, not rank 1, and would refute every genuine repair. dim here must equal R61's
  // axisSpanDim for the same axis and tensor.
  const rows: Fraction[][] = []
  for (let s = 0; s < DIM9; s += 1) {
    const row: Fraction[] = []
    for (let p = 0; p < DIM9; p += 1) {
      for (let q = 0; q < DIM9; q += 1) {
        const id = axis === 0 ? (s * DIM9 + p) * DIM9 + q : axis === 1 ? (p * DIM9 + s) * DIM9 + q : (p * DIM9 + q) * DIM9 + s
        row.push(fInt(D.get(id) ?? 0))
      }
    }
    rows.push(row)
  }
  // Column 9p+q of each wide row is the pair (p,q), which is exactly the coordinate toMat9
  // reads, so the span vector is the wide row sampled at its own column indices.
  return rowSpaceBasis(rows).map((wide) => {
    const out: Fraction[] = []
    for (let i = 0; i < DIM9 * DIM9; i += 1) out.push(wide[i] ?? fZero())
    return out
  })
}

/**
 * Restrict each quadric to two coordinates, returning (a, B, c) for a x^2 + B x y + c y^2.
 * The off-diagonal slot carries the factor 2 from lambda^T Q lambda = Q_ii x^2 + 2 Q_ik x y +
 * Q_kk y^2, so that callers never have to reintroduce it and get it wrong.
 */
function coerce(quads: readonly (readonly (readonly Fraction[])[])[], i: number, k: number): Conic[] {
  return quads.map((Q) => [
    Q[i]?.[i] ?? fZero(),
    fMul(fInt(2), Q[i]?.[k] ?? fZero()),
    Q[k]?.[k] ?? fZero(),
  ])
}

/**
 * Does the d-dimensional subspace spanned by `basis` (9-vectors) admit `dim S` linearly
 * independent vectors that reshape to 3x3 matrices of rank <= 1? Complete for d <= 3.
 */
export function segreSpan(basis: readonly (readonly Fraction[])[]): SegreSpanResult {
  const d = basis.length
  if (d === 0) return { complete: true, dim: 0, points: [], spanned: true }
  const quads = segreQuadrics(basis)
  if (d === 1) {
    const ok = !outsideSegre(quads, [fOne()])
    return { complete: true, dim: 1, points: ok ? [[fOne()]] : [], spanned: ok }
  }
  if (d === 2) {
    // Complete: P^1 is the chart y = 1 plus the single point (1,0) at y = 0, and on the chart
    // the first non-degenerate conic has at most two rational roots, found exactly.
    const pts = conicP1Zeros(coerce(quads, 0, 1))
    return { complete: true, dim: 2, points: pts, spanned: independentCount(pts) >= 2 }
  }
  if (d === 3) {
    // NOT complete, deliberately. When the span is generated by rank-1 matrices the Segre
    // intersection can be a positive-dimensional curve in P^2, and enumerating the roots of one
    // conic then returns only a couple of points of a set whose rank-1 members are the ones
    // that matter. Four charts are enumerated so the common case still finds its witnesses, but
    // a `spanned: false` here is NOT a refutation and must never be read as one.
    const pts: Fraction[][] = []
    for (const p of conicP1Zeros(coerce(quads, 0, 1))) {
      pts.push([p[0] ?? fZero(), p[1] ?? fZero(), fOne()])
      pts.push([p[0] ?? fZero(), p[1] ?? fZero(), fZero()])
    }
    for (const p of conicP1Zeros(coerce(quads, 0, 2))) {
      pts.push([p[0] ?? fZero(), fOne(), p[1] ?? fZero()])
    }
    for (const p of conicP1Zeros(coerce(quads, 1, 2))) {
      pts.push([fZero(), p[0] ?? fZero(), p[1] ?? fZero()])
    }
    const uniq: Fraction[][] = []
    for (const p of pts) if (!uniq.some((q) => sameProjective(q, p))) uniq.push(p)
    return { complete: false, dim: 3, points: uniq, spanned: independentCount(uniq) >= 3 }
  }
  return { complete: false, dim: d, points: [], spanned: false }
}

/** The 9-vector sum_i lambda_i basis[i]: does it reshape to rank <= 1? Independent cross-check. */
export function vectorInSegre(
  basis: readonly (readonly Fraction[])[],
  lam: readonly Fraction[],
): boolean {
  const out: Fraction[] = []
  for (let i = 0; i < DIM9 * DIM9; i += 1) {
    let acc = fZero()
    for (let k = 0; k < basis.length; k += 1) {
      const b = basis[k]?.[i] ?? fZero()
      const l = lam[k] ?? fZero()
      if (isZero(b) || isZero(l)) continue
      acc = fAdd(acc, fMul(b, l))
    }
    out.push(acc)
  }
  return rankOf(toMat9(out)) <= 1
}

export { fDiv, fMul, fSub, fZero, isZero, rref }
export type { Fraction }
